export const tldWhoisServers = {
  'com': 'whois.verisign-grs.com',
  'net': 'whois.verisign-grs.com',
  'org': 'whois.pir.org',
  'info': 'whois.afilias.net',
  'biz': 'whois.nic.biz',
  'name': 'whois.nic.name',
  'edu': 'whois.educause.edu',
  'gov': 'whois.dotgov.gov',
  'mil': 'whois.nic.mil',
  'int': 'whois.iana.org',
  'aero': 'whois.aero',
  'coop': 'whois.nic.coop',
  'museum': 'whois.nic.museum',
  'pro': 'whois.registry.pro',
  'tel': 'whois.nic.tel',
  'travel': 'whois.nic.travel',
  'xxx': 'whois.nic.xxx',
  'jobs': 'whois.nic.jobs',
  'mobi': 'whois.afilias.net',
  'asia': 'whois.nic.asia',
  'cat': 'whois.nic.cat',
  'post': 'whois.dotpostregistry.net',
  'ac': 'whois.nic.ac',
  'ad': 'whois.ripe.net',
  'ae': 'whois.aeda.net.ae',
  'af': 'whois.nic.af',
  'ag': 'whois.nic.ag',
  'ai': 'whois.nic.ai',
  'al': 'whois.ripe.net',
  'am': 'whois.amnic.net',
  'ao': 'whois.nic.ao',
  'aq': 'whois.nic.aq',
  'ar': 'whois.nic.ar',
  'as': 'whois.nic.as',
  'at': 'whois.nic.at',
  'au': 'whois.auda.org.au',
  'aw': 'whois.nic.aw',
  'ax': 'whois.ax',
  'az': 'whois.ripe.net',
  'ba': 'whois.ripe.net',
  'bb': 'whois.telecoms.gov.bb',
  'bd': 'whois.btcl.net.bd',
  'be': 'whois.dns.be',
  'bf': 'whois.nic.bf',
  'bg': 'whois.register.bg',
  'bh': 'whois.nic.bh',
  'bi': 'whois1.nic.bi',
  'bj': 'whois.nic.bj',
  'bm': 'whois.nic.bm',
  'bn': 'whois.bnnic.bn',
  'bo': 'whois.nic.bo',
  'br': 'whois.registro.br',
  'bs': 'whois.nic.bs',
  'bt': 'whois.netnames.net',
  'bw': 'whois.nic.net.bw',
  'by': 'whois.cctld.by',
  'bz': 'whois.afilias-grs.info',
  'ca': 'whois.cira.ca',
  'cc': 'ccwhois.verisign-grs.com',
  'cd': 'whois.nic.cd',
  'cf': 'whois.dot.cf',
  'cg': 'whois.nic.cg',
  'ch': 'whois.nic.ch',
  'ci': 'whois.nic.ci',
  'ck': 'whois.nic.ck',
  'cl': 'whois.nic.cl',
  'cm': 'whois.netcom.cm',
  'cn': 'whois.cnnic.cn',
  'co': 'whois.nic.co',
  'cr': 'whois.nic.cr',
  'cu': 'whois.nic.cu',
  'cv': 'whois.nic.cv',
  'cw': 'whois.nic.cw',
  'cx': 'whois.nic.cx',
  'cy': 'whois.nic.cy',
  'cz': 'whois.nic.cz',
  'de': 'whois.denic.de',
  'dj': 'whois.nic.dj',
  'dk': 'whois.punktum.dk',
  'dm': 'whois.dmdomains.dm',
  'do': 'whois.nic.do',
  'dz': 'whois.nic.dz',
  'ec': 'whois.nic.ec',
  'ee': 'whois.tld.ee',
  'eg': 'whois.ripe.net',
  'es': 'whois.nic.es',
  'et': 'whois.nic.et',
  'eu': 'whois.eu',
  'fi': 'whois.fi',
  'fj': 'whois.usp.ac.fj',
  'fk': 'whois.nic.fk',
  'fm': 'whois.nic.fm',
  'fo': 'whois.nic.fo',
  'fr': 'whois.afnic.fr',
  'ga': 'whois.nic.ga',
  'gd': 'whois.nic.gd',
  'ge': 'whois.nic.ge',
  'gf': 'whois.mediaserv.net',
  'gg': 'whois.gg',
  'gh': 'whois.nic.gh',
  'gi': 'whois2.afilias-grs.net',
  'gl': 'whois.nic.gl',
  'gm': 'whois.nic.gm',
  'gn': 'whois.ande.gov.gn',
  'gp': 'whois.nic.gp',
  'gq': 'whois.dominio.gq',
  'gr': 'whois.ripe.net',
  'gs': 'whois.nic.gs',
  'gt': 'whois.gt',
  'gu': 'whois.nic.gu',
  'gw': 'whois.nic.gw',
  'gy': 'whois.registry.gy',
  'hk': 'whois.hkirc.hk',
  'hm': 'whois.registry.hm',
  'hn': 'whois.nic.hn',
  'hr': 'whois.dns.hr',
  'ht': 'whois.nic.ht',
  'hu': 'whois.nic.hu',
  'id': 'whois.id',
  'ie': 'whois.weare.ie',
  'il': 'whois.isoc.org.il',
  'im': 'whois.nic.im',
  'in': 'whois.registry.in',
  'io': 'whois.nic.io',
  'iq': 'whois.cmc.iq',
  'ir': 'whois.nic.ir',
  'is': 'whois.isnic.is',
  'it': 'whois.nic.it',
  'je': 'whois.je',
  'jm': 'whois.mynic.jm',
  'jo': 'whois.nic.jo',
  'jp': 'whois.jprs.jp',
  'ke': 'whois.kenic.or.ke',
  'kg': 'whois.kg',
  'kh': 'whois.nic.kh',
  'ki': 'whois.nic.ki',
  'km': 'whois.nic.km',
  'kn': 'whois.nic.kn',
  'kp': 'whois.kcce.kp',
  'kr': 'whois.kr',
  'kw': 'whois.nic.kw',
  'ky': 'whois.kyregistry.ky',
  'kz': 'whois.nic.kz',
  'la': 'whois.nic.la',
  'lb': 'whois.lbdr.org.lb',
  'lc': 'whois.nic.lc',
  'li': 'whois.nic.li',
  'lk': 'whois.nic.lk',
  'lr': 'whois.nic.lr',
  'ls': 'whois.nic.ls',
  'lt': 'whois.domreg.lt',
  'lu': 'whois.restena.lu',
  'lv': 'whois.nic.lv',
  'ly': 'whois.nic.ly',
  'ma': 'whois.registre.ma',
  'mc': 'whois.ripe.net',
  'md': 'whois.nic.md',
  'me': 'whois.nic.me',
  'mg': 'whois.nic.mg',
  'mh': 'whois.nic.mh',
  'mk': 'whois.marnet.mk',
  'ml': 'whois.nic.ml',
  'mm': 'whois.registry.gov.mm',
  'mn': 'whois.nic.mn',
  'mo': 'whois.monic.mo',
  'mp': 'whois.nic.mp',
  'mq': 'whois.mediaserv.net',
  'mr': 'whois.nic.mr',
  'ms': 'whois.nic.ms',
  'mt': 'whois.nic.org.mt',
  'mu': 'whois.nic.mu',
  'mv': 'whois.nic.mv',
  'mw': 'whois.nic.mw',
  'mx': 'whois.mx',
  'my': 'whois.mynic.my',
  'mz': 'whois.nic.mz',
  'na': 'whois.na-nic.com.na',
  'nc': 'whois.nc',
  'ne': 'whois.nic.ne',
  'nf': 'whois.nic.nf',
  'ng': 'whois.nic.net.ng',
  'ni': 'whois.nic.ni',
  'nl': 'whois.domain-registry.nl',
  'no': 'whois.norid.no',
  'np': 'whois.nic.np',
  'nr': 'whois.nic.nr',
  'nu': 'whois.iis.nu',
  'nz': 'whois.irs.net.nz',
  'om': 'whois.registry.om',
  'pa': 'whois.nic.pa',
  'pe': 'kero.yachay.pe',
  'pf': 'whois.registry.pf',
  'pg': 'whois.nic.pg',
  'ph': 'whois.nic.ph',
  'pk': 'whois.pknic.net.pk',
  'pl': 'whois.dns.pl',
  'pm': 'whois.nic.pm',
  'pn': 'whois.nic.pn',
  'pr': 'whois.afilias-srs.net',
  'ps': 'whois.pnina.ps',
  'pt': 'whois.dns.pt',
  'pw': 'whois.nic.pw',
  'py': 'whois.nic.py',
  'qa': 'whois.registry.qa',
  're': 'whois.afnic.fr',
  'ro': 'whois.rotld.ro',
  'rs': 'whois.rnids.rs',
  'ru': 'whois.tcinet.ru',
  'rw': 'whois.ricta.org.rw',
  'sa': 'whois.nic.net.sa',
  'sb': 'whois.nic.sb',
  'sc': 'whois.nic.sc',
  'sd': 'whois.nic.sd',
  'se': 'whois.iis.se',
  'sg': 'whois.sgnic.sg',
  'sh': 'whois.nic.sh',
  'si': 'whois.register.si',
  'sk': 'whois.sk-nic.sk',
  'sl': 'whois.nic.sl',
  'sm': 'whois.nic.sm',
  'sn': 'whois.nic.sn',
  'so': 'whois.nic.so',
  'sr': 'whois.register.sr',
  'ss': 'whois.nic.ss',
  'st': 'whois.nic.st',
  'su': 'whois.tcinet.ru',
  'sv': 'whois.svnet.sv',
  'sx': 'whois.sx',
  'sy': 'whois.tld.sy',
  'sz': 'whois.nic.sz',
  'tc': 'whois.nic.tc',
  'td': 'whois.nic.td',
  'tf': 'whois.afnic.fr',
  'tg': 'whois.nic.tg',
  'th': 'whois.thnic.co.th',
  'tj': 'whois.nic.tj',
  'tk': 'whois.dot.tk',
  'tl': 'whois.nic.tl',
  'tm': 'whois.nic.tm',
  'tn': 'whois.ati.tn',
  'to': 'whois.tonic.to',
  'tr': 'whois.trabis.gov.tr',
  'tt': 'whois.nic.tt',
  'tv': 'tvwhois.verisign-grs.com',
  'tw': 'whois.twnic.net.tw',
  'tz': 'whois.tznic.or.tz',
  'ua': 'whois.ua',
  'ug': 'whois.co.ug',
  'uk': 'whois.nic.uk',
  'us': 'whois.nic.us',
  'uy': 'whois.nic.org.uy',
  'uz': 'whois.cctld.uz',
  'va': 'whois.nic.va',
  'vc': 'whois2.afilias-grs.net',
  've': 'whois.nic.ve',
  'vg': 'whois.nic.vg',
  'vi': 'whois.nic.vi',
  'vn': 'whois.nic.vn',
  'vu': 'whois.dnrs.vu',
  'wf': 'whois.afnic.fr',
  'ws': 'whois.website.ws',
  'ye': 'whois.y.net.ye',
  'yt': 'whois.afnic.fr',
  'za': 'whois.registry.net.za',
  'zm': 'whois.registry.zm',
  'zw': 'whois.nic.zw',
  '中国': 'whois.cnnic.cn',
  '中國': 'whois.cnnic.cn',
  '公司': 'whois.nic.xn--55qx5d',
  '网络': 'whois.nic.xn--io0a7i',
  '我爱你': 'whois.nic.xn--6qq986b3xl',
  '政务': 'whois.conac.cn',
  '游戏': 'whois.nic.xn--unup4y',
  'онлайн': 'whois.nic.xn--80asehdb',
  'сайт': 'whois.nic.xn--80aswg',
  '手机': 'whois.nic.xn--kput3i',
  '政府': 'whois.nic.xn--cg4bki',
  'გე': 'whois.nic.ge',
  '한국': 'whois.kr',
};

export const unregisteredPatterns = {
  'default': [
    /^no match/i,
    /^not found/i,
    /^no data found/i,
    /^no entries found/i,
    /^no matching record/i,
    /^object does not exist/i,
    /^not registered/i,
    /^%error: no entries found/i,
    /^domain not found/i,
    /^no information available/i,
    /^not exists/i,
    /^no such domain/i,
    /^query matched no objects/i,
    /^domain unknown/i,
    /^object not found/i,
    /^does not exist/i,
    /^no match for domain/i,
    /^nothing found/i,
    /^no data available/i,
    /^not been registered/i,
    /^no whois information/i,
    /^queried object does not exist/i,
    /^no match!/i,
    /^no match\./i,
    /^no matching objects found/i,
    /^no such data/i,
    /^domain you requested is not registered/i,
    /^no records matching/i,
    /^the queried object does not exist/i,
    /^domain cannot be found/i,
    /^no object found/i,
    /status:\s*available/i,
    /domain status:\s*available/i,
    /available for registration/i,
    /this domain is available for registration/i,
    /can be registered/i,
    /is free/i,
    /is available for purchase/i,
    /domain is available/i,
    /not found in registry/i,
    /no found/i,
    /domain not registered/i,
  ],
  'com': [
    /^no match for domain/i,
    /^no match for ".*\.com"/i,
    /^No match for domain ".*\.COM"/i,
    /^No match for ".*\.COM"/i,
  ],
  'net': [
    /^no match for domain/i,
    /^no match for ".*\.net"/i,
  ],
  'org': [
    /^not found:/i,
    /^not found\./i,
    /^not found/i,
  ],
  'ai': [
    /^domain not found\./i,
    /^not found/i,
    /^domain not found/i,
    /^no object found/i,
  ],
  'cn': [
    /no matching query/i,
    /not registered/i,
    /the domain has not been registered/i,
    /no matching query\./i,
  ],
  'de': [
    /status:\s*free/i,
    /not registered/i,
    /object does not exist/i,
  ],
  'fr': [
    /^%% no entries found/i,
    /not registered/i,
  ],
  'ru': [
    /not found/i,
    /не найден/i,
  ],
  'jp': [
    /no match!!/i,
    /not found/i,
  ],
  'kr': [
    /not found\./i,
    /above domain name is not registered/i,
  ],
  'io': [
    /^not found/i,
    /is available for purchase/i,
  ],
  'co': [
    /^not found/i,
    /^domain not found/i,
  ],
  'me': [
    /^not found/i,
  ],
};